{{- if eq .Values.gateway.enabled true }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: orion-default
  namespace: argocd
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}
